version: "3.7"

services:
  sphinx-relay:
    container_name: sphinx-relay
    image: sphinxlightning/sphinx-relay:v2.2.5@sha256:65fd26fec704f3f9041b9ca60aeb5c47f4bcd5f644f295ee58afe526e6780bb0
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${LND_DATA_DIR}:/lnd:ro
      - ${APP_DATA_DIR}/data:/relay/.lnd/
    ports:
      - "$APP_SPHINX_RELAY_PORT:$APP_SPHINX_RELAY_PORT"
    environment:
      PUBLIC_URL: "$APP_HIDDEN_SERVICE:$APP_SPHINX_RELAY_PORT"
      LND_IP: $LND_IP
      CONNECT_UI: "true"
      LND_PORT: $LND_GRPC_PORT
      TLS_LOCATION: /lnd/tls.cert
      MACAROON_LOCATION: /lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/admin.macaroon
      LND_LOG_LOCATION: /lnd/logs/bitcoin/${BITCOIN_NETWORK}/lnd.log
    networks:
      default:
        ipv4_address: $APP_SPHINX_RELAY_IP
